#References:
# Samples Database From: https://www.usabledatabases.com/database/books-isbn-covers/sample/#table_book

# WARNING: DO NOT EDIT THIS FILE

import csv          # Used to read a .csv file.
from random import randint
from random import seed

# Note: global variables are bad and should not be used in your code. ;) 
book_list:list = []      # Holds a list of books.
header:list = []         # Header for the list of books.

def getHeader() -> list:    
    """ Returned the information associated with each book in the book_list.
    :return : (list) the header information
    >>> readDatabase()
    >>> getHeader()
    ['title', 'author', 'authors', 'isbn10', 'format', 'publisher', 'pubdate', 'pages'] 
    """
    return header

def getRandomBook() -> list:
    """ Returns the information associated with a random book, stored as a list.
    :return : (list) the book information
    >>> readDatabase()
    >>> seed(123)
    >>> getRandomBook()
    ['How God Fix Jonah', 'Lorenz Graham', 'Lorenz Graham, Ashley Bryan (Illustrator), 
    Effie Lee Morris', '1563976986', 'Hardcover', 'Boyds Mills Press', 'Oct-00', '160']
    """
    num:int = randint(1,len(book_list)-1)
    return book_list[num]

def getRandomBookList(numBooks:int) -> list:
    """ Create and returns a list of random books. Each book is stored as a list. 
    :param numBook: (int) number of book the user wishes to return
    :return : (list) a list of books chosen randomly. The size of the list is based on the numBooks param.
    >>> readDatabase()
    >>> seed(123)
    >>> getRandomBookList(2)
    [['Basali!: Stories by and about Women in Lesotho', 'K. Limakatso Kendall', 
    'K. Limakatso Kendall', '869809180', 'Paperback', 'University of Natal Press', 'Feb-95', '136'], 
    ['How God Fix Jonah', 'Lorenz Graham', 'Lorenz Graham, Ashley Bryan (Illustrator), Effie Lee Morris',
    '1563976986', 'Hardcover', 'Boyds Mills Press', 'Oct-00', '160']]
    """
    num:int = randint(0,len(book_list)-1-numBooks)
    new_list:list = []
    for i in range(num, num+numBooks):
        new_list.append(book_list[i])
    return new_list

def readDatabase() -> int:
    """ Opens and reads the contents of 'book-database.csv'. Removed unnecessary columns (values) for each book.
    Populates global variable 'book_list' and 'header' for use by other functions. 
    :return : (int) the number of books read from the book database.
    >>> readDatabase()
    501
    """
    line_count:int = 0
    with open('book-database.csv') as csv_file:
        csv_reader = csv.reader(csv_file, delimiter=',')
        for row in csv_reader:
            if line_count == 0:
                row.remove(row[0])
                for element in row:
                    header.append(element)
                line_count += 1
            else:
                row.remove(row[0])
                book_list.append(row)
                line_count += 1
    return line_count

if __name__ == "__main__":
    print('Processed {0} lines.'.format(readDatabase()))
    print(f'Column names are {", ".join(header)}.')
else:
    readDatabase()
